//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockUp914.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCheck
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CheckId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Product Product { get; set; }
    }
}
